### ISSUE TITLE
Config parsing shouldn't fail silently.

### ISSUE THREAD

**Issue by altsem** [altsem/gitu#256]
Spawned from: https://github.com/altsem/gitu/issues/255

loading a config with invalid bindings fails silently:
```toml
[bindings]
root.quit = ["ctrl+g", "<esc>"]
```
