### ISSUE TITLE
push hangs infinitely when is push_menu.push configured

### ISSUE THREAD

**Issue by TLINDEN** [altsem/gitu#315]
Hi,

the default keys for push are `Pp` (`P` => push menu, `p` => actual push). This works as it should.

But when you configure the push key binding like this:

```toml
push_menu.push = ["p"]
```

... then push hangs forever with any repo. There's no error message whatsoever. However, it still responds to the `q` key to quit.

The same behavior can be witnessed, when you configure any other key for `push_menu.push`. Also, the changed key binding is not being displayed in the menu, it shows `p` even if - say - `f` is configured.

It **ONLY** works, if you don't touch that setting.

**Comment by altsem** [comment]
@TLINDEN I think I understand what is happening here.

`push_menu.push = ["p"]` this option has been removed in favor of:
```toml
push_menu.push_to_push_remote = ["p"]
push_menu.push_to_upstream = ["u"]
```
As well as for pulling:
```toml
pull_menu.pull_from_push_remote = ["p"]
pull_menu.pull_from_upstream = ["u"]
```
-which now is more akin to how Magit works.

Migrating to the new ones should fix the issues.

It seems that your binding take precedence over the default "push_to_push_remote" and Gitu does absolutely nothing. (I noticed I was still able to change flags/quit/run other commands in the menu).

Definitely strange behavior and should be fixed.
Perhaps there should be some validation on the config.
