### ISSUE TITLE
Short freeze on start

### ISSUE THREAD

**Issue by altsem** [altsem/gitu#333]
Gitu freezes for a second or so upon start. Seems like it does not occur with the file watcher disabled:

```toml
[general]
refresh_on_file_change.enabled = false
```

Is the file watcher causing unnecessary updates?
