### ISSUE TITLE
Better manage Tree-Sitter dependencies

### ISSUE THREAD

**Issue by altsem** [altsem/gitu#380]
Currently Gitu pulls in a bunch of tree-sitter grammars and a library to syntax-highlight code within diffs.
These are pinned in the Cargo.toml file to very specific versions (which happen to be compatible).
While pulling in these libraries worked out until now, it has some problems.

- It's a pain to upgrade them. We can only ever upgrade to the least-common-denominator (lowest version of them all).
- They increase the binary size quite a bit, and doesn't seem very sustainable (what if we want to include more languages?).
- Master doesn't build on windows anymore due to one of these. So something needs to be done. https://github.com/altsem/gitu/actions/runs/15365080988/job/43236925798

```toml
tree-sitter = "=0.20.10" # I think there's a 0.25 now, but the rest may not support it.
tree-sitter-highlight = "=0.20.1"
tree-sitter-rust = "=0.20.4"
tree-sitter-toml = "=0.20.0"
tree-sitter-javascript = "=0.20.4"
tree-sitter-c = "=0.20.8"
tree-sitter-json = "=0.20.2"
tree-sitter-cpp = "=0.20.5"
tree-sitter-ruby = "=0.20.1"
tree-sitter-haskell = "=0.15.0"
tree-sitter-go = "=0.20.0"
tree-sitter-c-sharp = "=0.20.0"
tree-sitter-python = "=0.20.4"
tree-sitter-typescript = "=0.20.5"
tree-sitter-bash = "=0.20.5"
tree-sitter-php = "=0.20.0"
tree-sitter-java = "=0.20.2"
tree-sitter-scala = "=0.20.3"
tree-sitter-ocaml = "=0.20.4"
tree-sitter-html = "=0.20.0"
tree-sitter-elixir = "=0.1.1" # <- Which version is this compatible with?
```
